name: Cardano Engineering
description: > # This mean ignore until the next property
  Cardano are building a world class open software platform and we want to share our thoughts,
  ideas, successes and failures with the world to help others.
url: https://cardano.github.io
email: engineering@cardano.com

markdown: kramdown
permalink: /blog/:year/:month/:day/:title
exclude: [docs/, lib/, scripts/]

port: 8080
# Listen on all interface so can connect from mobile on same network
# https://stackoverflow.com/questions/16608466/connect-to-a-locally-built-jekyll-server-using-mobile-devices-in-the-lan
host: 0.0.0.0

sass:
    sass_dir: _sass
